### ISSUE TITLE
Uncaught TypeError: a(...). replaceWith is not a function

### ISSUE THREAD

**Issue by abhirathore2006** [xdan/jodit2#1]
When i try to insert the list or ordered list without selecting the text it throws the error, i even tried this on your website but got same error.

can you Please fix it so a user can insert the  fresh list on cursor position

![screenshot from 2016-07-02 19-10-32](https://cloud.githubusercontent.com/assets/3352441/16540624/f3f0c310-4088-11e6-9f90-276cb3ffaa51.png)

**Comment by xdan** [comment]
Thank you, fixed in [2.3.27](http://xdsoft.net/jodit/doc/#toc11__anchor)
