### ISSUE TITLE
Set font size to auto always

### ISSUE THREAD

**Issue by abhirathore2006** [xdan/jodit2#10]
hi,

 is it possible to disable the font-size because i noticed that it automatically adds fontsize , i am using v2.3.27 
Also i want to support only the  basic html tags  like bold, strong, list and when somebody copy paste it just cleans everything and take only given above mention tags out of them

**Comment by xdan** [comment]
Added [allowTags](http://xdsoft.net/jodit/doc/Jodit.defaultOptions.html#cleanhtml) options
[More](http://xdsoft.net/jodit/doc/index.html#2.5.19)
