### ISSUE TITLE
Split mode for proffessionals is not working in Jodit

### ISSUE THREAD

**Issue by rig1** [xdan/jodit2#11]
I was trying to create a html text editor and i found a good match for my requirement in Jodit. But I coundn't able to implement it in my project. I have downloaded Jodit file and edited index.html to create a Split mode view. Still I 'am getting an text area. Follwoing is what i tried.

```
<body>
        <textarea id="split-editor" name="split-editor"></textarea>
</body>
<link rel="stylesheet" href="jodit.min.css">
<script src="jodit.min.js"></script>
<script>

    var editor = new Jodit('#split-editor', {
        defaultMode: Jodit.MODE_SPLIT
    });
    </script>
```

Can anyone say what is going wrong?

**Comment by xdan** [comment]
Fixed in 2.5.39. But this bug you could seen only in `file:` mode
