### ISSUE TITLE
 JSON.parse: unexpected character at line 1 column 1 of the JSON data #1 

### ISSUE THREAD

**Issue by ramnikwebs** [xdan/jodit2#2]
![599f9df0-35d3-11e6-8632-0cd786b4f3a3](https://cloud.githubusercontent.com/assets/20019495/16568671/9dde94de-424a-11e6-922f-b847571a9a66.jpg)

**Comment by xdan** [comment]
You should see that the server returns to the console. Probably he does not return JSON
